server:
  port: 8848
  forward-headers-strategy: native
  compression:
    enabled: false
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    add-properties: false
  output:
    ansi:
      enabled: always
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gra_blog?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: gao
logging:
  level:
    gra.gao.gra: warn
    root: info
  file:
    path: ${user.home}/.gra_blog/logs


mybatis:
  mapper-locations: mybatis/mapper/*.xml
